
FROM golang:1.19.4

# Source/Target release defaults
ARG ARCH=amd64
ARG GOARCH=amd64
ENV GO111MODULE=on GOOS=linux

WORKDIR /indra

# ENV defaults
# ENV IND_LOGFILEPATH=""

# Set the data volume
# VOLUME ["/var/indra"]

# :8337  indra peer-to-peer port
# :8338  indra RPC port
EXPOSE 8337 8338

ENTRYPOINT ["/indra/docker/sim/run.sh"]
