#!/bin/bash

docker run --rm -it --network=btcd_indranet \
  --volume=btcd_config:/etc/btcd:ro \
  --entrypoint="/bin/btcctl" \
 indralabs/btcctl:dev \
  -C /etc/btcd/btcctl.conf \
  --rpcserver=172.16.42.2:8334 \
  --rpcuser=simnet --rpcpass=simnet \
  --simnet $@
