#!/bin/bash

docker run --rm -it --network=btcd_indranet \
  --volume=btcd_config:/etc/btcd:ro \
 indralabs/btcctl-multi-arch:linux-amd64-dev \
  --rpcserver=172.16.42.2:8334 \
  --rpcuser=simnet --rpcpass=simnet \
  --simnet $@
