package address

import (
	"fmt"
	"github.com/indra-labs/indra"
	"github.com/indra-labs/indra/pkg/ad"
	"github.com/indra-labs/indra/pkg/crypto"
	"github.com/indra-labs/indra/pkg/crypto/nonce"
	"github.com/indra-labs/indra/pkg/crypto/sha256"
	"github.com/indra-labs/indra/pkg/engine/coding"
	"github.com/indra-labs/indra/pkg/engine/magic"
	"github.com/indra-labs/indra/pkg/engine/sess"
	"github.com/indra-labs/indra/pkg/onions/reg"
	log2 "github.com/indra-labs/indra/pkg/proc/log"
	"github.com/indra-labs/indra/pkg/util/multi"
	"github.com/indra-labs/indra/pkg/util/qu"
	"github.com/indra-labs/indra/pkg/util/splice"
	"github.com/multiformats/go-multiaddr"
	"net/netip"
	"reflect"
)

var (
	log   = log2.GetLogger(indra.PathBase)
	fails = log.E.Chk
)

const (
	Magic = "adad"
	Len   = magic.Len +
		nonce.IDLen +
		crypto.PubKeyLen +
		splice.AddrLen + 1 +
		crypto.SigLen
)

// Ad entries are stored with an index generated by concatenating the bytes
// of the public key with a string path "/address/N" where N is the index of the
// address. This means hidden service introducers for values over zero.
// Hidden services have no value in the zero index, which is "<hash>/address/0".
type Ad struct {
	ID   nonce.ID // To ensure no repeating message
	Key  *crypto.Pub
	Addr multiaddr.Multiaddr
	Sig  crypto.SigBytes
}

func (x *Ad) Decode(s *splice.Splice) (e error) {
	if e = magic.TooShort(s.Remaining(), Len-magic.Len,
		Magic); fails(e) {

		return
	}
	addr := &netip.AddrPort{}
	s.ReadID(&x.ID).
		ReadPubkey(&x.Key).
		ReadAddrPort(&addr).
		ReadSignature(&x.Sig)
	//cid.Parse(x.Key.ToBytes())
	var ap multiaddr.Multiaddr
	proto := "ip4"
	if addr.Addr().Is6() {
		proto = "ip6"
	}
	if ap, e = multiaddr.NewMultiaddr(
		"/" + proto + "/" + addr.Addr().String() +
			"/tcp/" + fmt.Sprint(addr.Port()),
	); fails(e) {
		return
	}
	x.Addr = multi.AddKeyToMultiaddr(ap, x.Key)
	return
}

func (x *Ad) Encode(s *splice.Splice) (e error) {
	log.T.S("encoding", reflect.TypeOf(x),
		x.ID, x.Sig,
	)
	x.Splice(s)
	return
}

func (x *Ad) GetOnion() interface{} { return x }

func (x *Ad) Gossip(sm *sess.Manager, c qu.C) {
	log.D.F("propagating peer info for %s",
		x.Key.ToBased32Abbreviated())
	ad.Gossip(x, sm, c)
	log.T.Ln("finished broadcasting peer info")
}

func (x *Ad) Len() int { return Len }

func (x *Ad) Magic() string { return Magic }

func (x *Ad) Splice(s *splice.Splice) {
	x.SpliceWithoutSig(s)
	s.Signature(x.Sig)
}

func (x *Ad) SpliceWithoutSig(s *splice.Splice) {
	var e error
	var ap netip.AddrPort
	if ap, e = multi.AddrToAddrPort(x.Addr); fails(e) {
		return
	}
	s.Magic(Magic).
		ID(x.ID).
		Pubkey(x.Key).
		AddrPort(&ap)
}

func (x *Ad) Validate() bool {
	s := splice.New(Len - magic.Len)
	x.SpliceWithoutSig(s)
	hash := sha256.Single(s.GetUntil(s.GetCursor()))
	key, e := x.Sig.Recover(hash)
	if fails(e) {
		return false
	}
	if key.Equals(x.Key) {
		return true
	}
	return false
}

func NewAddressAd(id nonce.ID, key *crypto.Prv,
	ma multiaddr.Multiaddr) (peerAd *Ad) {

	pub := crypto.DerivePub(key)
	ma = multi.AddKeyToMultiaddr(ma, pub)
	log.D.Ln("ma", ma)
	peerAd = &Ad{
		ID:   id,
		Key:  pub,
		Addr: ma,
	}
	s := splice.New(Len - magic.Len)
	peerAd.SpliceWithoutSig(s)
	hash := sha256.Single(s.GetUntil(s.GetCursor()))
	var e error
	if peerAd.Sig, e = crypto.Sign(key, hash); fails(e) {
		return nil
	}
	return
}

func addrGen() coding.Codec { return &Ad{} }

func init() { reg.Register(Magic, addrGen) }
