package nonce

import (
	"crypto/rand"
	"encoding/base32"
	
	"github.com/gookit/color"
	
	"git-indra.lan/indra-labs/indra/pkg/crypto/sha256"
)

const IDLen = 8

// ID is a value generated by the first 8 bytes truncated from the values of a
// hash chain that reseeds from a CSPRNG at first use and every time it
// generates 2^16 (65536) new ID's.
type ID [IDLen]byte

var enc = base32.NewEncoding(Charset).EncodeToString

const Charset = "abcdefghijklmnopqrstuvwxyz234679"

func (id ID) String() string {
	return color.LightBlue.Sprint(enc(id[:])[:13])
}

var seed sha256.Hash
var counter uint16

func reseed() {
	if c, e := rand.Read(seed[:]); fails(e) && c != IDLen {
	}
	counter++
}

// NewID returns a random 8 byte nonce to be used as identifiers.
func NewID() (t ID) {
	if counter == 0 {
		reseed()
	}
	s := sha256.Single(seed[:])
	copy(seed[:], s[:])
	copy(t[:], seed[:IDLen])
	return
}
