package nonce

import (
	"crypto/rand"
	"encoding/base32"
	
	"github.com/gookit/color"
)

const IDLen = 8

// ID is a value generated by a hash chain that renews at first use and every
// time it generates 2^32 new ID's.
type ID [IDLen]byte

var enc = base32.NewEncoding(Charset).EncodeToString

const Charset = "abcdefghijklmnopqrstuvwxyz234679"

func (id ID) String() string {
	return color.LightBlue.Sprint(enc(id[:])[:13])
}

// NewID returns a random 8 byte nonce to be used as identifiers.
func NewID() (t ID) {
	if read, e := rand.Read(t[:]); check(e) && read != IDLen {
	}
	return
}
